server {
    listen 80;
    server_name wall-admin.wdbzk.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name wall-admin.wdbzk.com;

    ssl_certificate     /www/server/panel/vhost/cert/wall-admin.wdbzk.com/fullchain.pem;
    ssl_certificate_key /www/server/panel/vhost/cert/wall-admin.wdbzk.com/privkey.pem;

    root /www/wwwroot/wallpaper-manager/apps/admin/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
